spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.security.web.access: DEBUG
    hexlet.code: DEBUG
